author:
  name: Vasiliy Kharitonov
  email: "vasiliy.kharitonov@icloud.com"

minima:
  skin: dark
  social_links:
    twitter: kh4rit
    github: Vslow
    linkedin: kharit
    telegram: Vslow

# theme: minima
remote_theme: jekyll/minima

url: "https://blog.kharit.xyz" # the base hostname & protocol
permalink: /:categories/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Google Analytics
google_analytics: UA-45730869-7
