author:
  name: Vasiliy
  email: "vasiliy@kharit.xyz"

minima:
  skin: light
  social_links:
    twitter: kh4rit
    github: kh4rit
    linkedin: kharit
    telegram: kh4rit

# theme: minima
remote_theme: jekyll/minima

url: "https://kharit.blog" # the base hostname & protocol
permalink: /:categories/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Google Analytics
google_analytics: G-W5FTXWMXYB
