title: kharit.blog
description: A personal blog

author:
  email: "vasiliy@kharit.xyz"

minima:
  social_links:
    twitter: kh4rit
    github: kh4rit
    linkedin: kharit
    telegram: kh4rit

<<<<<<< HEAD
theme: minima
=======
# theme: minima
remote_theme: jekyll/minima
>>>>>>> aaca9bbebcf08ca6466fbd985658d0dea6e80300

url: "https://kharit.blog" # the base hostname & protocol
permalink: /:categories/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Google Analytics
google_analytics: G-W5FTXWMXYB
