title: kharit.blog
description: A personal blog

author:
  email: "vasiliy@kharit.xyz"

header_pages:
  - about.md

theme: minima

minima:
  social_links:
    twitter: kh4rit
    github: kh4rit
    linkedin: kharit
    telegram: kh4rit
  skin: classic
  date_format: "%d %b %Y"
  disqus:
    shortname: kharit-blog

url: "https://kharit.blog" # the base hostname & protocol
permalink: /:categories/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-scholar
#  - jekyll-sitemap # can't be used with GitHub Pages

# Google Analytics
google_analytics: G-W5FTXWMXYB
