title: kharit.blog
description: A personal blog

author:
  email: "vasiliy@kharit.xyz"

minima:
  social_links:
    twitter: kh4rit
    github: kh4rit
    linkedin: kharit
    telegram: kh4rit

theme: minima

url: "https://kharit.blog" # the base hostname & protocol
permalink: /:categories/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-scholar

# Google Analytics
google_analytics: G-W5FTXWMXYB
